#-----------------------------------------------------------------------------
# Copyright (c) 2026 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Controlling KTLIB debug prints
# Enable for detailed debug prints
# TBD-DPN: Needs to be better organized, currently enabled in Makefile
#-----------------------------------------------------------------------------
# DEFINES += KT_DEBUG

export